apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server-deployment
  labels:
    env: test
    app: server
spec:
  selector:
    matchLabels:
      app: my-server
  template:
    metadata:
      labels:
        app: my-server
    spec:
      containers:
        - name: container-my-server
          image: smirnoff410/cloudcs-lab2:server
          ports:
            - containerPort: 8000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-server-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 80